#loc = loc("ir_00_torch_input.mlir":1:1)
#loc5 = loc("ir_00_torch_input.mlir":2:3)
#loc6 = loc("step_a_iree_input.mlir":2:32)
#loc7 = loc("step_a_iree_input.mlir":2:57)
#loc8 = loc("step_a_iree_input.mlir":2:82)
#loc9 = loc("step_a_iree_input.mlir":2:101)
#loc28 = loc("step_a_iree_input.mlir":13:26)
#loc29 = loc("step_a_iree_input.mlir":13:51)
module @module attributes {vm.toplevel} {
  vm.module public @module {
    vm.global.ref private mutable @__device_0 : !vm.ref<!hal.device> loc(#loc)
    vm.global.ref private mutable @__device_0_executable_0_main$async_dispatch_0 : !vm.ref<!hal.executable> loc(#loc1)
    vm.global.ref private mutable @__main$async_memoize_result_0_device_0 : !vm.ref<!hal.command_buffer> loc(#loc1)
    vm.rodata private @_utf8_hal_device_id_C6650FF277232B5A {alignment = 1 : i64} "hal.device.id" loc(#loc)
    vm.rodata private @_utf8_local_1A8FF0278D7661D8 {alignment = 1 : i64} "local*" loc(#loc)
    vm.rodata private @_utf8_hal_executable_format_E03EECB63A2AAF52 {alignment = 1 : i64} "hal.executable.format" loc(#loc30)
    vm.rodata private @_utf8_embedded_elf_x86_64_FF16E34B4A5F9C83 {alignment = 1 : i64} "embedded-elf-x86_64" loc(#loc30)
    vm.rodata private @main_async_dispatch_0_embedded_elf_x86_64 {alignment = 16 : i64, mime_type = "application/x-elf"} dense_resource<__elided__> : vector<5432xi8> loc(#loc1)
    vm.func private @__main$async_memoize_apply() -> !vm.ref<!hal.command_buffer> attributes {inlining_policy = #util.inline.never, vm.unwind} {
      %c13 = vm.const.i32 13 loc(#loc1)
      %c28 = vm.const.i32 28 loc(#loc1)
      %c2 = vm.const.i32 2 loc(#loc1)
      %null = vm.const.ref.zero : !vm.ref<!hal.buffer> loc(#loc2)
      %c1 = vm.const.i32 1 loc(#loc2)
      %c16 = vm.const.i32 16 loc(#loc2)
      %c3 = vm.const.i32 3 loc(#loc2)
      %zero = vm.const.i32.zero loc(#loc2)
      %c65536 = vm.const.i64 65536 loc(#loc3)
      %zero_0 = vm.const.i64.zero loc(#loc2)
      %c-1 = vm.const.i64 -1 loc(#loc1)
      %__device_0 = vm.global.load.ref @__device_0 : !vm.ref<!hal.device> loc(#loc1)
      %__device_0_executable_0_main$async_dispatch_0 = vm.global.load.ref @__device_0_executable_0_main$async_dispatch_0 : !vm.ref<!hal.executable> loc(#loc1)
      %ref = vm.call @hal.command_buffer.create(%__device_0, %zero, %c3, %c-1, %c3) : (!vm.ref<!hal.device>, i32, i32, i64, i32) -> !vm.ref<!hal.command_buffer> loc(#loc1)
      vm.call.variadic @hal.command_buffer.dispatch(%ref, %__device_0_executable_0_main$async_dispatch_0, %zero, %c16, %c1, %c1, %zero_0, [], [(%zero, %zero, %null, %zero_0, %c65536), (%zero, %c1, %null, %zero_0, %c65536), (%zero, %c2, %null, %zero_0, %c65536)]) : (!vm.ref<!hal.command_buffer>, !vm.ref<!hal.executable>, i32, i32, i32, i32, i64, i32 ..., tuple<i32, i32, !vm.ref<!hal.buffer>, i64, i64> ...) loc(#loc1)
      vm.call @hal.command_buffer.execution_barrier(%ref, %c28, %c13, %zero_0) : (!vm.ref<!hal.command_buffer>, i32, i32, i64) -> () loc(#loc1)
      vm.call @hal.command_buffer.finalize(%ref) : (!vm.ref<!hal.command_buffer>) -> () loc(#loc1)
      vm.return %ref : !vm.ref<!hal.command_buffer> loc(#loc1)
    } loc(#loc1)
    vm.rodata private @_utf8_tensor_FC1814BC4A58F22A {alignment = 1 : i64} "tensor" loc(#loc31)
    vm.func private @main$async(%arg0: !vm.ref<!hal.buffer_view> loc("step_a_iree_input.mlir":2:32), %arg1: !vm.ref<!hal.buffer_view> loc("step_a_iree_input.mlir":2:57), %arg2: !vm.ref<!hal.fence> loc("step_a_iree_input.mlir":2:82), %arg3: !vm.ref<!hal.fence> loc("step_a_iree_input.mlir":2:101)) -> !vm.ref<!hal.buffer_view> attributes {inlining_policy = #util.inline.never, vm.unwind} {
      %c16 = vm.const.i32 16 loc(#loc2)
      %c1 = vm.const.i32 1 loc(#loc3)
      %c553648160 = vm.const.i32 553648160 loc(#loc3)
      %c3075 = vm.const.i32 3075 loc(#loc2)
      %c48 = vm.const.i32 48 loc(#loc1)
      %c128 = vm.const.i64 128 loc(#loc2)
      %c65536 = vm.const.i64 65536 loc(#loc3)
      %zero = vm.const.i64.zero loc(#loc2)
      %c-1 = vm.const.i64 -1 loc(#loc2)
      %__device_0 = vm.global.load.ref @__device_0 : !vm.ref<!hal.device> loc(#loc3)
      %__main$async_memoize_result_0_device_0 = vm.global.load.ref @__main$async_memoize_result_0_device_0 : !vm.ref<!hal.command_buffer> loc(#loc1)
      %_utf8_tensor_FC1814BC4A58F22A = vm.const.ref.rodata @_utf8_tensor_FC1814BC4A58F22A : !vm.buffer loc(#loc3)
      vm.call.variadic @hal.buffer_view.assert(%arg0, %_utf8_tensor_FC1814BC4A58F22A, %c553648160, %c1, [%c128, %c128]) : (!vm.ref<!hal.buffer_view>, !vm.buffer, i32, i32, i64 ...) loc(#loc3)
      %ref = vm.call @hal.buffer_view.buffer(%arg0) {nosideeffects} : (!vm.ref<!hal.buffer_view>) -> !vm.ref<!hal.buffer> loc(#loc3)
      %ref_0 = vm.call @hal.device.allocator(%__device_0) {nosideeffects} : (!vm.ref<!hal.device>) -> !vm.ref<!hal.allocator> loc(#loc3)
      vm.call @hal.buffer.assert(%ref, %_utf8_tensor_FC1814BC4A58F22A, %ref_0, %c65536, %c16, %c3075) : (!vm.ref<!hal.buffer>, !vm.buffer, !vm.ref<!hal.allocator>, i64, i32, i32) -> () loc(#loc3)
      vm.call.variadic @hal.buffer_view.assert(%arg1, %_utf8_tensor_FC1814BC4A58F22A, %c553648160, %c1, [%c128, %c128]) : (!vm.ref<!hal.buffer_view>, !vm.buffer, i32, i32, i64 ...) loc(#loc4)
      %ref_1 = vm.call @hal.buffer_view.buffer(%arg1) {nosideeffects} : (!vm.ref<!hal.buffer_view>) -> !vm.ref<!hal.buffer> loc(#loc4)
      vm.call @hal.buffer.assert(%ref_1, %_utf8_tensor_FC1814BC4A58F22A, %ref_0, %c65536, %c16, %c3075) : (!vm.ref<!hal.buffer>, !vm.buffer, !vm.ref<!hal.allocator>, i64, i32, i32) -> () loc(#loc4)
      %ref_2 = vm.call @hal.fence.create(%__device_0, %zero) : (!vm.ref<!hal.device>, i64) -> !vm.ref<!hal.fence> loc(#loc1)
      %ref_3 = vm.call @hal.device.queue.alloca(%__device_0, %c-1, %arg2, %ref_2, %zero, %c48, %c3075, %c65536, %zero) : (!vm.ref<!hal.device>, i64, !vm.ref<!hal.fence>, !vm.ref<!hal.fence>, i64, i32, i32, i64, i64) -> !vm.ref<!hal.buffer> loc(#loc1)
      vm.call.variadic @hal.device.queue.execute.indirect(%__device_0, %c-1, %ref_2, %arg3, %__main$async_memoize_result_0_device_0, %zero, [(%ref, %zero, %c65536), (%ref_1, %zero, %c65536), (%ref_3, %zero, %c65536)]) : (!vm.ref<!hal.device>, i64, !vm.ref<!hal.fence>, !vm.ref<!hal.fence>, !vm.ref<!hal.command_buffer>, i64, tuple<!vm.ref<!hal.buffer>, i64, i64> ...) loc(#loc1)
      %ref_4 = vm.call.variadic @hal.buffer_view.create(%ref_3, %zero, %c65536, %c553648160, %c1, [%c128, %c128]) {nosideeffects} : (!vm.ref<!hal.buffer>, i64, i64, i32, i32, i64 ...) -> !vm.ref<!hal.buffer_view> loc(#loc5)
      vm.return %ref_4 : !vm.ref<!hal.buffer_view> loc(#loc10)
    } loc(#loc5)
    vm.export @main$async attributes {iree.abi.model = "coarse-fences", iree.abi.stub} loc(#loc5)
    vm.import private @hal.buffer.assert(%buffer : !vm.ref<!hal.buffer>, %message : !vm.buffer, %allocator : !vm.ref<!hal.allocator>, %minimum_length : i64, %memory_types : i32, %buffer_usage : i32) loc(#loc11)
    vm.import private @hal.buffer_view.create(%buffer : !vm.ref<!hal.buffer>, %source_offset : i64, %source_length : i64, %element_type : i32, %encoding_type : i32, %shape : i64 ...) -> !vm.ref<!hal.buffer_view> attributes {nosideeffects} loc(#loc12)
    vm.import private @hal.buffer_view.assert(%buffer_view : !vm.ref<!hal.buffer_view>, %message : !vm.buffer, %element_type : i32, %encoding_type : i32, %shape : i64 ...) loc(#loc13)
    vm.import private @hal.buffer_view.buffer(%buffer_view : !vm.ref<!hal.buffer_view>) -> !vm.ref<!hal.buffer> attributes {nosideeffects} loc(#loc14)
    vm.import private @hal.command_buffer.create(%device : !vm.ref<!hal.device>, %modes : i32, %command_categories : i32, %queue_affinity : i64, %binding_capacity : i32) -> !vm.ref<!hal.command_buffer> attributes {minimum_version = 6 : i32} loc(#loc15)
    vm.import private @hal.command_buffer.finalize(%command_buffer : !vm.ref<!hal.command_buffer>) loc(#loc16)
    vm.import private @hal.command_buffer.execution_barrier(%command_buffer : !vm.ref<!hal.command_buffer>, %source_stage_mask : i32, %target_stage_mask : i32, %flags : i64) loc(#loc17)
    vm.import private @hal.command_buffer.dispatch(%command_buffer : !vm.ref<!hal.command_buffer>, %executable : !vm.ref<!hal.executable>, %entry_point : i32, %workgroup_x : i32, %workgroup_y : i32, %workgroup_z : i32, %flags : i64, %constants : i32 ..., %bindings : tuple<i32, i32, !vm.ref<!hal.buffer>, i64, i64> ...) loc(#loc18)
    vm.import private @hal.device.allocator(%device : !vm.ref<!hal.device>) -> !vm.ref<!hal.allocator> attributes {nosideeffects} loc(#loc19)
    vm.import private @hal.device.query.i64(%device : !vm.ref<!hal.device>, %category : !vm.buffer, %key : !vm.buffer) -> (i32, i64) attributes {nosideeffects} loc(#loc20)
    vm.import private @hal.device.queue.alloca(%device : !vm.ref<!hal.device>, %queue_affinity : i64, %wait_fence : !vm.ref<!hal.fence>, %signal_fence : !vm.ref<!hal.fence>, %pool : i64, %memory_types : i32, %buffer_usage : i32, %allocation_size : i64, %flags : i64) -> !vm.ref<!hal.buffer> loc(#loc21)
    vm.import private @hal.device.queue.execute.indirect(%device : !vm.ref<!hal.device>, %queue_affinity : i64, %wait_fence : !vm.ref<!hal.fence>, %signal_fence : !vm.ref<!hal.fence>, %command_buffer : !vm.ref<!hal.command_buffer>, %flags : i64, %binding_table : tuple<!vm.ref<!hal.buffer>, i64, i64> ...) loc(#loc22)
    vm.import private @hal.devices.count() -> i32 attributes {nosideeffects} loc(#loc23)
    vm.import private @hal.devices.get(%index : i32) -> !vm.ref<!hal.device> attributes {nosideeffects} loc(#loc24)
    vm.import private @hal.executable.create(%device : !vm.ref<!hal.device>, %queue_affinity : i64, %executable_format : !vm.buffer, %executable_data : !vm.buffer, %constants : !vm.buffer) -> !vm.ref<!hal.executable> attributes {nosideeffects} loc(#loc25)
    vm.import private @hal.fence.create(%device : !vm.ref<!hal.device>, %flags : i64) -> !vm.ref<!hal.fence> loc(#loc26)
    vm.import private @hal.fence.await(%timeout_millis : i32, %flags : i64, %fences : !vm.ref<!hal.fence> ...) -> i32 attributes {vm.yield} loc(#loc27)
    vm.func private @main(%arg0: !vm.ref<!hal.buffer_view> loc("step_a_iree_input.mlir":13:26), %arg1: !vm.ref<!hal.buffer_view> loc("step_a_iree_input.mlir":13:51)) -> !vm.ref<!hal.buffer_view> attributes {vm.unwind, vm.yield} {
      %null = vm.const.ref.zero : !vm.ref<!hal.fence> loc(#loc5)
      %c-1 = vm.const.i32 -1 loc(#loc5)
      %zero = vm.const.i64.zero loc(#loc2)
      %zero_0 = vm.const.i32.zero loc(#loc5)
      %ref = vm.call @hal.devices.get(%zero_0) {nosideeffects} : (i32) -> !vm.ref<!hal.device> loc(#loc5)
      %ref_1 = vm.call @hal.fence.create(%ref, %zero) : (!vm.ref<!hal.device>, i64) -> !vm.ref<!hal.fence> loc(#loc5)
      %ref_2 = vm.call @main$async(%arg0, %arg1, %null, %ref_1) : (!vm.ref<!hal.buffer_view>, !vm.ref<!hal.buffer_view>, !vm.ref<!hal.fence>, !vm.ref<!hal.fence>) -> !vm.ref<!hal.buffer_view> loc(#loc5)
      vm.call.variadic.yieldable @hal.fence.await(%c-1, %zero, %ref_1) {segment_sizes = dense<[-1, -1, 1]> : vector<3xi16>, segment_types = [i32, i64, !vm.ref<!hal.fence>]} : (i32, i64, !vm.ref<!hal.fence>) -> ^bb1 (i32) loc(#loc5)
    ^bb1(%0: i32 loc("ir_00_torch_input.mlir":2:3)):  // pred: ^bb0
      vm.return %ref_2 : !vm.ref<!hal.buffer_view> loc(#loc5)
    } loc(#loc5)
    vm.export @main attributes {iree.abi.stub} loc(#loc5)
    vm.export @__init loc(#loc2)
    vm.func private @__init() attributes {vm.unwind} {
      %c1 = vm.const.i32 1 loc(#loc2)
      %null = vm.const.ref.zero : !vm.buffer loc(#loc2)
      %c14 = vm.const.i32 14 loc(#loc2)
      %c-1 = vm.const.i64 -1 loc(#loc2)
      %c18 = vm.const.i32 18 loc(#loc2)
      %zero = vm.const.i32.zero loc(#loc2)
      %zero_0 = vm.const.i64.zero loc(#loc2)
      %c1_1 = vm.const.i64 1 loc(#loc)
      %null_2 = vm.const.ref.zero : !vm.ref<!hal.device> loc(#loc2)
      %0 = vm.call @hal.devices.count() {nosideeffects} : () -> i32 loc(#loc)
      %1 = vm.ext.i32.i64.s %0 : i32 -> i64 loc(#loc)
      vm.br ^bb1(%zero_0, %zero_0, %null_2 : i64, i64, !vm.ref<!hal.device>) loc(#loc)
    ^bb1(%2: i64 loc("ir_00_torch_input.mlir":1:1), %3: i64 loc("ir_00_torch_input.mlir":1:1), %4: !vm.ref<!hal.device> loc("ir_00_torch_input.mlir":1:1)):  // 2 preds: ^bb0, ^bb4
      %rnz = vm.cmp.nz.ref %4 : !vm.ref<!hal.device> loc(#loc)
      %5 = vm.xor.i32 %rnz, %c1 : i32 loc(#loc)
      %slt = vm.cmp.lt.i64.s %2, %1 : i64 loc(#loc)
      %6 = vm.and.i32 %5, %slt : i32 loc(#loc)
      vm.cond_br %6, ^bb2, ^bb5 loc(#loc)
    ^bb2:  // pred: ^bb1
      vm.discard.refs %4 : !vm.ref<!hal.device> loc(#loc)
      %7 = vm.trunc.i64.i32 %2 : i64 -> i32 loc(#loc)
      %ref = vm.call @hal.devices.get(%7) {nosideeffects} : (i32) -> !vm.ref<!hal.device> loc(#loc)
      %_utf8_hal_device_id_C6650FF277232B5A = vm.const.ref.rodata @_utf8_hal_device_id_C6650FF277232B5A : !vm.buffer loc(#loc)
      %_utf8_local_1A8FF0278D7661D8 = vm.const.ref.rodata @_utf8_local_1A8FF0278D7661D8 : !vm.buffer loc(#loc)
      %8:2 = vm.call @hal.device.query.i64(%ref, %_utf8_hal_device_id_C6650FF277232B5A, %_utf8_local_1A8FF0278D7661D8) {nosideeffects} : (!vm.ref<!hal.device>, !vm.buffer, !vm.buffer) -> (i32, i64) loc(#loc)
      %nz = vm.cmp.nz.i64 %8#1 : i64 loc(#loc)
      %9 = vm.select.i32 %8#0, %nz, %zero : i32 loc(#loc)
      vm.cond_br %9, ^bb3, ^bb4(%zero : i32) loc(#loc)
    ^bb3:  // pred: ^bb2
      %_utf8_hal_executable_format_E03EECB63A2AAF52 = vm.const.ref.rodata @_utf8_hal_executable_format_E03EECB63A2AAF52 : !vm.buffer loc(#loc)
      %_utf8_embedded_elf_x86_64_FF16E34B4A5F9C83 = vm.const.ref.rodata @_utf8_embedded_elf_x86_64_FF16E34B4A5F9C83 : !vm.buffer loc(#loc)
      %10:2 = vm.call @hal.device.query.i64(%ref, %_utf8_hal_executable_format_E03EECB63A2AAF52, %_utf8_embedded_elf_x86_64_FF16E34B4A5F9C83) {nosideeffects} : (!vm.ref<!hal.device>, !vm.buffer, !vm.buffer) -> (i32, i64) loc(#loc)
      %nz_3 = vm.cmp.nz.i64 %10#1 : i64 loc(#loc)
      %11 = vm.select.i32 %10#0, %nz_3, %zero : i32 loc(#loc)
      vm.br ^bb4(%11 : i32) loc(#loc)
    ^bb4(%12: i32 loc("ir_00_torch_input.mlir":1:1)):  // 2 preds: ^bb2, ^bb3
      %eq = vm.cmp.eq.i64 %3, %zero_0 : i64 loc(#loc)
      %13 = vm.select.i64 %12, %c1_1, %zero_0 : i64 loc(#loc)
      %14 = vm.add.i64 %3, %13 : i64 loc(#loc)
      %15 = vm.and.i32 %12, %eq : i32 loc(#loc)
      %ref_4 = vm.select.ref %15, %ref, %null_2 : !vm.ref<!hal.device> loc(#loc)
      %16 = vm.add.i64 %2, %c1_1 : i64 loc(#loc)
      vm.br ^bb1(%16, %14, %ref_4 : i64, i64, !vm.ref<!hal.device>) loc(#loc)
    ^bb5:  // pred: ^bb1
      vm.discard.refs %null_2 : !vm.ref<!hal.device> loc(#loc)
      vm.cond_br %5, ^bb6, ^bb7 loc(#loc)
    ^bb6:  // pred: ^bb5
      vm.discard.refs %null, %4 : !vm.buffer, !vm.ref<!hal.device> loc(#loc)
      vm.fail %c18, "HAL device `__device_0` not found or unavailable: #hal.device.target<\22local\22, [#hal.executable.target<\22llvm-cpu\22, \22embedded-elf-x86_64\22, {cpu = \22znver5\22, cpu_features = \22+64bit,+adx,+aes,-amx-avx512,-amx-bf16,-amx-complex,-amx-fp16,-amx-fp8,-amx-int8,-amx-movrs,-amx-tf32,-amx-tile,+avx,-avx10.1,-avx10.2,+avx2,-avx512bf16,-avx512bitalg,+avx512bw,+avx512cd,+avx512dq,+avx512f,-avx512fp16,-avx512ifma,-avx512vbmi,-avx512vbmi2,+avx512vl,-avx512vnni,-avx512vp2intersect,-avx512vpopcntdq,-avxifma,-avxneconvert,-avxvnni,-avxvnniint16,-avxvnniint8,+bmi,+bmi2,-ccmp,-cf,-cldemote,+clflushopt,+clwb,+clzero,+cmov,-cmpccxadd,+crc32,+cx16,+cx8,-egpr,-enqcmd,+f16c,+fma,-fma4,+fsgsbase,+fxsr,-gfni,-hreset,+invpcid,-kl,-lwp,+lzcnt,+mmx,+movbe,-movdir64b,-movdiri,-movrs,-mwaitx,-ndd,-nf,+pclmul,-pconfig,+pku,+popcnt,-ppx,-prefetchi,+prfchw,-ptwrite,-push2pop2,-raoint,-rdpid,-rdpru,+rdrnd,+rdseed,-rtm,+sahf,-serialize,-sgx,+sha,-sha512,-shstk,-sm3,-sm4,+sse,+sse2,+sse3,+sse4.1,+sse4.2,+sse4a,+ssse3,-tbm,-tsxldtrk,-uintr,-usermsr,-vaes,-vpclmulqdq,-waitpkg,-wbnoinvd,-widekl,-xop,+xsave,+xsavec,+xsaveopt,+xsaves,-zu\22, data_layout = \22e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128\22, iree.encoding.resolver = #iree_cpu.cpu_encoding_resolver<>, max_stack_allocation_size = 32768 : i64, native_vector_size = 64 : i64, target_triple = \22x86_64-unknown-unknown-eabi-elf\22}>]>" loc(#loc)
    ^bb7:  // pred: ^bb5
      %_utf8_hal_executable_format_E03EECB63A2AAF52_5 = vm.const.ref.rodata @_utf8_hal_executable_format_E03EECB63A2AAF52 : !vm.buffer loc(#loc1)
      %_utf8_embedded_elf_x86_64_FF16E34B4A5F9C83_6 = vm.const.ref.rodata @_utf8_embedded_elf_x86_64_FF16E34B4A5F9C83 : !vm.buffer loc(#loc1)
      %17:2 = vm.call @hal.device.query.i64(%4, %_utf8_hal_executable_format_E03EECB63A2AAF52_5, %_utf8_embedded_elf_x86_64_FF16E34B4A5F9C83_6) {nosideeffects} : (!vm.ref<!hal.device>, !vm.buffer, !vm.buffer) -> (i32, i64) loc(#loc1)
      %nz_7 = vm.cmp.nz.i64 %17#1 : i64 loc(#loc1)
      %18 = vm.select.i32 %17#0, %nz_7, %zero : i32 loc(#loc1)
      %19 = vm.select.i64 %18, %zero_0, %c-1 : i64 loc(#loc1)
      %eq_8 = vm.cmp.eq.i64 %19, %zero_0 : i64 loc(#loc1)
      vm.global.store.ref %4, @__device_0 : !vm.ref<!hal.device> loc(#loc)
      vm.cond_br %eq_8, ^bb8, ^bb9 loc(#loc1)
    ^bb8:  // pred: ^bb7
      %main_async_dispatch_0_embedded_elf_x86_64 = vm.const.ref.rodata @main_async_dispatch_0_embedded_elf_x86_64 : !vm.buffer loc(#loc1)
      %ref_9 = vm.call @hal.executable.create(%4, %c-1, %_utf8_embedded_elf_x86_64_FF16E34B4A5F9C83_6, %main_async_dispatch_0_embedded_elf_x86_64, %null) {nosideeffects} : (!vm.ref<!hal.device>, i64, !vm.buffer, !vm.buffer, !vm.buffer) -> !vm.ref<!hal.executable> loc(#loc1)
      vm.global.store.ref %ref_9, @__device_0_executable_0_main$async_dispatch_0 : !vm.ref<!hal.executable> loc(#loc1)
      %ref_10 = vm.call @__main$async_memoize_apply() : () -> !vm.ref<!hal.command_buffer> loc(#loc1)
      vm.global.store.ref %ref_10, @__main$async_memoize_result_0_device_0 : !vm.ref<!hal.command_buffer> loc(#loc1)
      vm.return loc(#loc2)
    ^bb9:  // pred: ^bb7
      vm.discard.refs %null, %4, %_utf8_embedded_elf_x86_64_FF16E34B4A5F9C83_6 : !vm.buffer, !vm.ref<!hal.device>, !vm.buffer loc(#loc1)
      vm.fail %c14, "HAL device `__device_0` does not support any variant of executable `main$async_dispatch_0`; available formats: [embedded-elf-x86_64]" loc(#loc1)
    } loc(#loc2)
  } loc(#loc)
} loc(#loc)
#loc1 = loc("ir_00_torch_input.mlir":3:10)
#loc2 = loc(unknown)
#loc3 = loc("ir_00_torch_input.mlir":2:19)
#loc4 = loc("ir_00_torch_input.mlir":2:57)
#loc10 = loc("ir_00_torch_input.mlir":4:5)
#loc11 = loc("-":66:1)
#loc12 = loc("-":130:1)
#loc13 = loc("-":141:1)
#loc14 = loc("-":150:1)
#loc15 = loc("-":222:1)
#loc16 = loc("-":235:1)
#loc17 = loc("-":253:1)
#loc18 = loc("-":331:1)
#loc19 = loc("-":365:1)
#loc20 = loc("-":371:1)
#loc21 = loc("-":381:1)
#loc22 = loc("-":499:1)
#loc23 = loc("-":522:1)
#loc24 = loc("-":525:1)
#loc25 = loc("-":533:1)
#loc26 = loc("-":547:1)
#loc27 = loc("-":579:1)
#loc30 = loc(fused[#loc, #loc1])
#loc31 = loc(fused[#loc3, #loc4])

