hal.executable public @main$async_dispatch_7 {
  hal.executable.variant public @embedded_elf_x86_64 target(<"llvm-cpu", "embedded-elf-x86_64", {cpu = "znver5", cpu_features = "+64bit,+adx,+aes,-amx-avx512,-amx-bf16,-amx-complex,-amx-fp16,-amx-fp8,-amx-int8,-amx-movrs,-amx-tf32,-amx-tile,+avx,-avx10.1,-avx10.2,+avx2,-avx512bf16,-avx512bitalg,+avx512bw,+avx512cd,+avx512dq,+avx512f,-avx512fp16,-avx512ifma,-avx512vbmi,-avx512vbmi2,+avx512vl,-avx512vnni,-avx512vp2intersect,-avx512vpopcntdq,-avxifma,-avxneconvert,-avxvnni,-avxvnniint16,-avxvnniint8,+bmi,+bmi2,-ccmp,-cf,-cldemote,+clflushopt,+clwb,+clzero,+cmov,-cmpccxadd,+crc32,+cx16,+cx8,-egpr,-enqcmd,+f16c,+fma,-fma4,+fsgsbase,+fxsr,-gfni,-hreset,+invpcid,-kl,-lwp,+lzcnt,+mmx,+movbe,-movdir64b,-movdiri,-movrs,-mwaitx,-ndd,-nf,+pclmul,-pconfig,+pku,+popcnt,-ppx,-prefetchi,+prfchw,-ptwrite,-push2pop2,-raoint,-rdpid,-rdpru,+rdrnd,+rdseed,-rtm,+sahf,-serialize,-sgx,+sha,-sha512,-shstk,-sm3,-sm4,+sse,+sse2,+sse3,+sse4.1,+sse4.2,+sse4a,+ssse3,-tbm,-tsxldtrk,-uintr,-usermsr,-vaes,-vpclmulqdq,-waitpkg,-wbnoinvd,-widekl,-xop,+xsave,+xsavec,+xsaveopt,+xsaves,-zu", data_layout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128", iree.encoding.resolver = #iree_cpu.cpu_encoding_resolver<>, max_stack_allocation_size = 32768 : i64, native_vector_size = 64 : i64, target_triple = "x86_64-unknown-unknown-eabi-elf"}>) {
    hal.executable.export public @main$async_dispatch_7_batch_matmul_1x16x32x32_f32 ordinal(0) layout(#hal.pipeline.layout<constants = 2, bindings = [#hal.pipeline.binding<storage_buffer, "ReadOnly|Indirect">, #hal.pipeline.binding<storage_buffer, ReadOnly>, #hal.pipeline.binding<storage_buffer, Indirect>], flags = Indirect>) count(%arg0: !hal.device loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":96:11)) -> (index, index, index) {
      %x, %y, %z = iree_tensor_ext.dispatch.workgroup_count_from_slice() loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":96:11)
      hal.return %x, %y, %z : index, index, index loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":96:11)
    } loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":96:11)
    builtin.module {
      func.func @main$async_dispatch_7_batch_matmul_1x16x32x32_f32() {
        %cst = arith.constant 0.000000e+00 : f32 loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":91:11)
        %c0 = arith.constant 0 : index loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":96:11)
        %0 = hal.interface.constant.load layout(<constants = 2, bindings = [#hal.pipeline.binding<storage_buffer, "ReadOnly|Indirect">, #hal.pipeline.binding<storage_buffer, ReadOnly>, #hal.pipeline.binding<storage_buffer, Indirect>], flags = Indirect>) ordinal(0) : i32 loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":96:11)
        %1 = hal.interface.constant.load layout(<constants = 2, bindings = [#hal.pipeline.binding<storage_buffer, "ReadOnly|Indirect">, #hal.pipeline.binding<storage_buffer, ReadOnly>, #hal.pipeline.binding<storage_buffer, Indirect>], flags = Indirect>) ordinal(1) : i32 loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":96:11)
        %2 = arith.index_castui %0 : i32 to index loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":96:11)
        %3 = arith.index_castui %1 : i32 to index loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":96:11)
        %4:2 = util.assume.int 
            %2[<umin = 0, umax = 0>, <umin = 4096, umax = 4096, udiv = 4096>, <umin = 8192, umax = 8192, udiv = 8192>, <umin = 25856, umax = 25856, udiv = 25856>, <umin = 29952, umax = 29952, udiv = 29952>, <umin = 34048, umax = 34048, udiv = 34048>, <umin = 51712, umax = 51712, udiv = 51712>, <umin = 55808, umax = 55808, udiv = 55808>, <umin = 59904, umax = 59904, udiv = 59904>, <umin = 77568, umax = 77568, udiv = 77568>, <umin = 81664, umax = 81664, udiv = 81664>, <umin = 85760, umax = 85760, udiv = 85760>, <umin = 103424, umax = 103424, udiv = 103424>, <umin = 107520, umax = 107520, udiv = 107520>, <umin = 111616, umax = 111616, udiv = 111616>], 
            %3[<umin = 2048, umax = 2048, udiv = 2048>, <umin = 6144, umax = 6144, udiv = 6144>, <umin = 8192, umax = 8192, udiv = 8192>, <umin = 2048, umax = 2048, udiv = 2048>, <umin = 6144, umax = 6144, udiv = 6144>, <umin = 8192, umax = 8192, udiv = 8192>, <umin = 2048, umax = 2048, udiv = 2048>, <umin = 6144, umax = 6144, udiv = 6144>, <umin = 8192, umax = 8192, udiv = 8192>, <umin = 2048, umax = 2048, udiv = 2048>, <umin = 6144, umax = 6144, udiv = 6144>, <umin = 8192, umax = 8192, udiv = 8192>, <umin = 2048, umax = 2048, udiv = 2048>, <umin = 6144, umax = 6144, udiv = 6144>, <umin = 8192, umax = 8192, udiv = 8192>]
          : index, index loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":96:11)
        %5 = hal.interface.binding.subspan layout(<constants = 2, bindings = [#hal.pipeline.binding<storage_buffer, "ReadOnly|Indirect">, #hal.pipeline.binding<storage_buffer, ReadOnly>, #hal.pipeline.binding<storage_buffer, Indirect>], flags = Indirect>) binding(0) alignment(64) offset(%c0) flags("ReadOnly|Indirect") : !iree_tensor_ext.dispatch.tensor<readonly:tensor<1x16x32xf32>> loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":91:11)
        %6 = hal.interface.binding.subspan layout(<constants = 2, bindings = [#hal.pipeline.binding<storage_buffer, "ReadOnly|Indirect">, #hal.pipeline.binding<storage_buffer, ReadOnly>, #hal.pipeline.binding<storage_buffer, Indirect>], flags = Indirect>) binding(1) alignment(64) offset(%4#0) flags(ReadOnly) : !iree_tensor_ext.dispatch.tensor<readonly:tensor<1x32x32xf32>> loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":96:11)
        %7 = hal.interface.binding.subspan layout(<constants = 2, bindings = [#hal.pipeline.binding<storage_buffer, "ReadOnly|Indirect">, #hal.pipeline.binding<storage_buffer, ReadOnly>, #hal.pipeline.binding<storage_buffer, Indirect>], flags = Indirect>) binding(2) alignment(64) offset(%4#1) flags(Indirect) : !iree_tensor_ext.dispatch.tensor<writeonly:tensor<1x16x32xf32>> loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":96:11)
        %8 = iree_tensor_ext.dispatch.tensor.load %5, offsets = [0, 0, 0], sizes = [1, 16, 32], strides = [1, 1, 1] : !iree_tensor_ext.dispatch.tensor<readonly:tensor<1x16x32xf32>> -> tensor<1x16x32xf32> loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":96:11)
        %9 = iree_tensor_ext.dispatch.tensor.load %6, offsets = [0, 0, 0], sizes = [1, 32, 32], strides = [1, 1, 1] : !iree_tensor_ext.dispatch.tensor<readonly:tensor<1x32x32xf32>> -> tensor<1x32x32xf32> loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":96:11)
        %10 = tensor.empty() : tensor<1x16x32xf32> loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":69:11)
        %11 = linalg.fill ins(%cst : f32) outs(%10 : tensor<1x16x32xf32>) -> tensor<1x16x32xf32> loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":96:11)
        %12 = linalg.batch_matmul ins(%8, %9 : tensor<1x16x32xf32>, tensor<1x32x32xf32>) outs(%11 : tensor<1x16x32xf32>) -> tensor<1x16x32xf32> loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":96:11)
        iree_tensor_ext.dispatch.tensor.store %12, %7, offsets = [0, 0, 0], sizes = [1, 16, 32], strides = [1, 1, 1] : tensor<1x16x32xf32> -> !iree_tensor_ext.dispatch.tensor<writeonly:tensor<1x16x32xf32>> loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":96:11)
        return loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":96:11)
      } loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":96:11)
    } loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":96:11)
  } loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":96:11)
} loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":96:11)
