hal.executable public @main$async_dispatch_13 {
  hal.executable.variant public @embedded_elf_x86_64 target(<"llvm-cpu", "embedded-elf-x86_64", {cpu = "znver5", cpu_features = "+64bit,+adx,+aes,-amx-avx512,-amx-bf16,-amx-complex,-amx-fp16,-amx-fp8,-amx-int8,-amx-movrs,-amx-tf32,-amx-tile,+avx,-avx10.1,-avx10.2,+avx2,-avx512bf16,-avx512bitalg,+avx512bw,+avx512cd,+avx512dq,+avx512f,-avx512fp16,-avx512ifma,-avx512vbmi,-avx512vbmi2,+avx512vl,-avx512vnni,-avx512vp2intersect,-avx512vpopcntdq,-avxifma,-avxneconvert,-avxvnni,-avxvnniint16,-avxvnniint8,+bmi,+bmi2,-ccmp,-cf,-cldemote,+clflushopt,+clwb,+clzero,+cmov,-cmpccxadd,+crc32,+cx16,+cx8,-egpr,-enqcmd,+f16c,+fma,-fma4,+fsgsbase,+fxsr,-gfni,-hreset,+invpcid,-kl,-lwp,+lzcnt,+mmx,+movbe,-movdir64b,-movdiri,-movrs,-mwaitx,-ndd,-nf,+pclmul,-pconfig,+pku,+popcnt,-ppx,-prefetchi,+prfchw,-ptwrite,-push2pop2,-raoint,-rdpid,-rdpru,+rdrnd,+rdseed,-rtm,+sahf,-serialize,-sgx,+sha,-sha512,-shstk,-sm3,-sm4,+sse,+sse2,+sse3,+sse4.1,+sse4.2,+sse4a,+ssse3,-tbm,-tsxldtrk,-uintr,-usermsr,-vaes,-vpclmulqdq,-waitpkg,-wbnoinvd,-widekl,-xop,+xsave,+xsavec,+xsaveopt,+xsaves,-zu", data_layout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128", iree.encoding.resolver = #iree_cpu.cpu_encoding_resolver<>, max_stack_allocation_size = 32768 : i64, native_vector_size = 64 : i64, target_triple = "x86_64-unknown-unknown-eabi-elf"}>) {
    hal.executable.export public @main$async_dispatch_13_attention_4x16x8x8x16 ordinal(0) layout(#hal.pipeline.layout<bindings = [#hal.pipeline.binding<storage_buffer, "ReadOnly|Indirect">, #hal.pipeline.binding<storage_buffer, "ReadOnly|Indirect">, #hal.pipeline.binding<storage_buffer, Indirect>], flags = Indirect>) count(%arg0: !hal.device loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":134:11)) -> (index, index, index) {
      %x, %y, %z = iree_tensor_ext.dispatch.workgroup_count_from_slice() loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":134:11)
      hal.return %x, %y, %z : index, index, index loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":134:11)
    } loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":134:11)
    builtin.module {
      func.func @main$async_dispatch_13_attention_4x16x8x8x16() {
        %cst = arith.constant 0.353553385 : f32 loc(unknown)
        %c4096 = arith.constant 4096 : index loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":134:11)
        %c2048 = arith.constant 2048 : index loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":134:11)
        %c6144 = arith.constant 6144 : index loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":134:11)
        %c0 = arith.constant 0 : index loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":134:11)
        %c8192 = arith.constant 8192 : index loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":134:11)
        %0 = hal.interface.binding.subspan layout(<bindings = [#hal.pipeline.binding<storage_buffer, "ReadOnly|Indirect">, #hal.pipeline.binding<storage_buffer, "ReadOnly|Indirect">, #hal.pipeline.binding<storage_buffer, Indirect>], flags = Indirect>) binding(0) alignment(64) offset(%c4096) flags("ReadOnly|Indirect") : !iree_tensor_ext.dispatch.tensor<readonly:tensor<4x16x8xf32>> loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":96:11)
        %1 = hal.interface.binding.subspan layout(<bindings = [#hal.pipeline.binding<storage_buffer, "ReadOnly|Indirect">, #hal.pipeline.binding<storage_buffer, "ReadOnly|Indirect">, #hal.pipeline.binding<storage_buffer, Indirect>], flags = Indirect>) binding(0) alignment(64) offset(%c2048) flags("ReadOnly|Indirect") : !iree_tensor_ext.dispatch.tensor<readonly:tensor<4x16x8xf32>> loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":108:11)
        %2 = hal.interface.binding.subspan layout(<bindings = [#hal.pipeline.binding<storage_buffer, "ReadOnly|Indirect">, #hal.pipeline.binding<storage_buffer, "ReadOnly|Indirect">, #hal.pipeline.binding<storage_buffer, Indirect>], flags = Indirect>) binding(0) alignment(64) offset(%c6144) flags("ReadOnly|Indirect") : !iree_tensor_ext.dispatch.tensor<readonly:tensor<4x8x16xf32>> loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":120:11)
        %3 = hal.interface.binding.subspan layout(<bindings = [#hal.pipeline.binding<storage_buffer, "ReadOnly|Indirect">, #hal.pipeline.binding<storage_buffer, "ReadOnly|Indirect">, #hal.pipeline.binding<storage_buffer, Indirect>], flags = Indirect>) binding(1) alignment(64) offset(%c0) flags("ReadOnly|Indirect") : !iree_tensor_ext.dispatch.tensor<readonly:tensor<16x16xf32>> loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":134:11)
        %4 = hal.interface.binding.subspan layout(<bindings = [#hal.pipeline.binding<storage_buffer, "ReadOnly|Indirect">, #hal.pipeline.binding<storage_buffer, "ReadOnly|Indirect">, #hal.pipeline.binding<storage_buffer, Indirect>], flags = Indirect>) binding(2) alignment(64) offset(%c8192) flags(Indirect) : !iree_tensor_ext.dispatch.tensor<writeonly:tensor<16x4x8xf32>> loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":134:11)
        %5 = iree_tensor_ext.dispatch.tensor.load %0, offsets = [0, 0, 0], sizes = [4, 16, 8], strides = [1, 1, 1] : !iree_tensor_ext.dispatch.tensor<readonly:tensor<4x16x8xf32>> -> tensor<4x16x8xf32> loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":134:11)
        %6 = iree_tensor_ext.dispatch.tensor.load %1, offsets = [0, 0, 0], sizes = [4, 16, 8], strides = [1, 1, 1] : !iree_tensor_ext.dispatch.tensor<readonly:tensor<4x16x8xf32>> -> tensor<4x16x8xf32> loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":134:11)
        %7 = iree_tensor_ext.dispatch.tensor.load %2, offsets = [0, 0, 0], sizes = [4, 8, 16], strides = [1, 1, 1] : !iree_tensor_ext.dispatch.tensor<readonly:tensor<4x8x16xf32>> -> tensor<4x8x16xf32> loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":134:11)
        %8 = iree_tensor_ext.dispatch.tensor.load %3, offsets = [0, 0], sizes = [16, 16], strides = [1, 1] : !iree_tensor_ext.dispatch.tensor<readonly:tensor<16x16xf32>> -> tensor<16x16xf32> loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":134:11)
        %9 = tensor.empty() : tensor<4x16x8xf32> loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":134:11)
        %10 = iree_linalg_ext.attention {indexing_maps = [affine_map<(d0, d1, d2, d3, d4) -> (d0, d1, d3)>, affine_map<(d0, d1, d2, d3, d4) -> (d0, d4, d3)>, affine_map<(d0, d1, d2, d3, d4) -> (d0, d2, d4)>, affine_map<(d0, d1, d2, d3, d4) -> ()>, affine_map<(d0, d1, d2, d3, d4) -> (d1, d4)>, affine_map<(d0, d1, d2, d3, d4) -> (d0, d1, d2)>]} ins(%5, %6, %7, %cst, %8 : tensor<4x16x8xf32>, tensor<4x16x8xf32>, tensor<4x8x16xf32>, f32, tensor<16x16xf32>) outs(%9 : tensor<4x16x8xf32>) {
        ^bb0(%arg0: f32 loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":134:11)):
          iree_linalg_ext.yield %arg0 : f32 loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":134:11)
        } -> tensor<4x16x8xf32> loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":134:11)
        %11 = tensor.empty() : tensor<16x4x8xf32> loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":137:11)
        %12 = linalg.generic {indexing_maps = [affine_map<(d0, d1, d2) -> (d0, d1, d2)>, affine_map<(d0, d1, d2) -> (d1, d0, d2)>], iterator_types = ["parallel", "parallel", "parallel"]} ins(%10 : tensor<4x16x8xf32>) outs(%11 : tensor<16x4x8xf32>) {
        ^bb0(%in: f32 loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":137:11), %out: f32 loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":137:11)):
          linalg.yield %in : f32 loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":137:11)
        } -> tensor<16x4x8xf32> loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":137:11)
        iree_tensor_ext.dispatch.tensor.store %12, %4, offsets = [0, 0, 0], sizes = [16, 4, 8], strides = [1, 1, 1] : tensor<16x4x8xf32> -> !iree_tensor_ext.dispatch.tensor<writeonly:tensor<16x4x8xf32>> loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":134:11)
        return loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":134:11)
      } loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":134:11)
    } loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":134:11)
  } loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":134:11)
} loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":134:11)
