hal.executable public @main$async_dispatch_1 {
  hal.executable.variant public @embedded_elf_x86_64 target(<"llvm-cpu", "embedded-elf-x86_64", {cpu = "znver5", cpu_features = "+64bit,+adx,+aes,-amx-avx512,-amx-bf16,-amx-complex,-amx-fp16,-amx-fp8,-amx-int8,-amx-movrs,-amx-tf32,-amx-tile,+avx,-avx10.1,-avx10.2,+avx2,-avx512bf16,-avx512bitalg,+avx512bw,+avx512cd,+avx512dq,+avx512f,-avx512fp16,-avx512ifma,-avx512vbmi,-avx512vbmi2,+avx512vl,-avx512vnni,-avx512vp2intersect,-avx512vpopcntdq,-avxifma,-avxneconvert,-avxvnni,-avxvnniint16,-avxvnniint8,+bmi,+bmi2,-ccmp,-cf,-cldemote,+clflushopt,+clwb,+clzero,+cmov,-cmpccxadd,+crc32,+cx16,+cx8,-egpr,-enqcmd,+f16c,+fma,-fma4,+fsgsbase,+fxsr,-gfni,-hreset,+invpcid,-kl,-lwp,+lzcnt,+mmx,+movbe,-movdir64b,-movdiri,-movrs,-mwaitx,-ndd,-nf,+pclmul,-pconfig,+pku,+popcnt,-ppx,-prefetchi,+prfchw,-ptwrite,-push2pop2,-raoint,-rdpid,-rdpru,+rdrnd,+rdseed,-rtm,+sahf,-serialize,-sgx,+sha,-sha512,-shstk,-sm3,-sm4,+sse,+sse2,+sse3,+sse4.1,+sse4.2,+sse4a,+ssse3,-tbm,-tsxldtrk,-uintr,-usermsr,-vaes,-vpclmulqdq,-waitpkg,-wbnoinvd,-widekl,-xop,+xsave,+xsavec,+xsaveopt,+xsaves,-zu", data_layout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128", iree.encoding.resolver = #iree_cpu.cpu_encoding_resolver<>, max_stack_allocation_size = 32768 : i64, native_vector_size = 64 : i64, target_triple = "x86_64-unknown-unknown-eabi-elf"}>) {
    hal.executable.export public @main$async_dispatch_1_scan_1x16xi64_dispatch_tensor_store ordinal(0) layout(#hal.pipeline.layout<bindings = [#hal.pipeline.binding<storage_buffer, "ReadOnly|Indirect">, #hal.pipeline.binding<storage_buffer, Indirect>], flags = Indirect>) count(%arg0: !hal.device loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":27:10)) -> (index, index, index) {
      %x, %y, %z = iree_tensor_ext.dispatch.workgroup_count_from_slice() loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":27:10)
      hal.return %x, %y, %z : index, index, index loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":27:10)
    } loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":27:10)
    builtin.module {
      func.func @main$async_dispatch_1_scan_1x16xi64_dispatch_tensor_store() {
        %c0_i64 = arith.constant 0 : i64 loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":31:10)
        %c0 = arith.constant 0 : index loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":27:10)
        %c64 = arith.constant 64 : index loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":27:10)
        %0 = hal.interface.binding.subspan layout(<bindings = [#hal.pipeline.binding<storage_buffer, "ReadOnly|Indirect">, #hal.pipeline.binding<storage_buffer, Indirect>], flags = Indirect>) binding(0) alignment(64) offset(%c0) flags("ReadOnly|Indirect") : !iree_tensor_ext.dispatch.tensor<readonly:tensor<1x16xi32>> loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":27:10)
        %1 = hal.interface.binding.subspan layout(<bindings = [#hal.pipeline.binding<storage_buffer, "ReadOnly|Indirect">, #hal.pipeline.binding<storage_buffer, Indirect>], flags = Indirect>) binding(1) alignment(64) offset(%c64) flags(Indirect) : !iree_tensor_ext.dispatch.tensor<writeonly:tensor<1x16xi64>> loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":27:10)
        %2 = iree_tensor_ext.dispatch.tensor.load %0, offsets = [0, 0], sizes = [1, 16], strides = [1, 1] : !iree_tensor_ext.dispatch.tensor<readonly:tensor<1x16xi32>> -> tensor<1x16xi32> loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":27:10)
        %3 = tensor.empty() : tensor<1xi64> loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":27:10)
        %4 = tensor.empty() : tensor<1x16xi64> loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":27:10)
        %5 = linalg.generic {indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = ["parallel", "parallel"]} ins(%2 : tensor<1x16xi32>) outs(%4 : tensor<1x16xi64>) {
        ^bb0(%in: i32 loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":24:10), %out: i64 loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":27:10)):
          %9 = arith.extsi %in : i32 to i64 loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":27:10)
          linalg.yield %9 : i64 loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":27:10)
        } -> tensor<1x16xi64> loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":27:10)
        %6 = linalg.fill ins(%c0_i64 : i64) outs(%3 : tensor<1xi64>) -> tensor<1xi64> loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":27:10)
        %7 = linalg.fill ins(%c0_i64 : i64) outs(%4 : tensor<1x16xi64>) -> tensor<1x16xi64> loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":27:10)
        %8:2 = iree_linalg_ext.scan {operandSegmentSizes = array<i32: 1, 2>} dimension(1) inclusive(true) ins(%5 : tensor<1x16xi64>) outs(%7, %6 : tensor<1x16xi64>, tensor<1xi64>) {
        ^bb0(%arg0: i64 loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":27:10), %arg1: i64 loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":27:10)):
          %9 = arith.addi %arg0, %arg1 : i64 loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":27:10)
          iree_linalg_ext.yield %9 : i64 loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":27:10)
        } -> tensor<1x16xi64>, tensor<1xi64> loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":27:10)
        iree_tensor_ext.dispatch.tensor.store %8#0, %1, offsets = [0, 0], sizes = [1, 16], strides = [1, 1] : tensor<1x16xi64> -> !iree_tensor_ext.dispatch.tensor<writeonly:tensor<1x16xi64>> loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":27:10)
        return loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":27:10)
      } loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":27:10)
    } loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":27:10)
  } loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":27:10)
} loc("/local/mnt/workspace/compilers/CompilerLens/examples/hf-internal-testing_tiny-random-RobertaModel/_full/ir_00_torch_input.mlir":27:10)
