hal.executable public @main$async_dispatch_21 {
  hal.executable.variant public @embedded_elf_x86_64 target(<"llvm-cpu", "embedded-elf-x86_64", {cpu = "znver5", cpu_features = "+64bit,+adx,+aes,-amx-avx512,-amx-bf16,-amx-complex,-amx-fp16,-amx-fp8,-amx-int8,-amx-movrs,-amx-tf32,-amx-tile,+avx,-avx10.1,-avx10.2,+avx2,-avx512bf16,-avx512bitalg,+avx512bw,+avx512cd,+avx512dq,+avx512f,-avx512fp16,-avx512ifma,-avx512vbmi,-avx512vbmi2,+avx512vl,-avx512vnni,-avx512vp2intersect,-avx512vpopcntdq,-avxifma,-avxneconvert,-avxvnni,-avxvnniint16,-avxvnniint8,+bmi,+bmi2,-ccmp,-cf,-cldemote,+clflushopt,+clwb,+clzero,+cmov,-cmpccxadd,+crc32,+cx16,+cx8,-egpr,-enqcmd,+f16c,+fma,-fma4,+fsgsbase,+fxsr,-gfni,-hreset,+invpcid,-kl,-lwp,+lzcnt,+mmx,+movbe,-movdir64b,-movdiri,-movrs,-mwaitx,-ndd,-nf,+pclmul,-pconfig,+pku,+popcnt,-ppx,-prefetchi,+prfchw,-ptwrite,-push2pop2,-raoint,-rdpid,-rdpru,+rdrnd,+rdseed,-rtm,+sahf,-serialize,-sgx,+sha,-sha512,-shstk,-sm3,-sm4,+sse,+sse2,+sse3,+sse4.1,+sse4.2,+sse4a,+ssse3,-tbm,-tsxldtrk,-uintr,-usermsr,-vaes,-vpclmulqdq,-waitpkg,-wbnoinvd,-widekl,-xop,+xsave,+xsavec,+xsaveopt,+xsaves,-zu", data_layout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128", iree.encoding.resolver = #iree_cpu.cpu_encoding_resolver<>, max_stack_allocation_size = 32768 : i64, native_vector_size = 64 : i64, target_triple = "x86_64-unknown-unknown-eabi-elf"}>) {
    hal.executable.export public @main$async_dispatch_21_batch_matmul_1x16x50257x2_f32 ordinal(0) layout(#hal.pipeline.layout<bindings = [#hal.pipeline.binding<storage_buffer, "ReadOnly|Indirect">, #hal.pipeline.binding<storage_buffer, ReadOnly>, #hal.pipeline.binding<storage_buffer, Indirect>], flags = Indirect>) count(%arg0: !hal.device loc("/local/mnt/workspace/compilers/CompilerLens/examples/sshleifer_tiny-gpt2/_full/ir_00_torch_input.mlir":362:12)) -> (index, index, index) {
      %x, %y, %z = iree_tensor_ext.dispatch.workgroup_count_from_slice() loc("/local/mnt/workspace/compilers/CompilerLens/examples/sshleifer_tiny-gpt2/_full/ir_00_torch_input.mlir":362:12)
      hal.return %x, %y, %z : index, index, index loc("/local/mnt/workspace/compilers/CompilerLens/examples/sshleifer_tiny-gpt2/_full/ir_00_torch_input.mlir":362:12)
    } loc("/local/mnt/workspace/compilers/CompilerLens/examples/sshleifer_tiny-gpt2/_full/ir_00_torch_input.mlir":362:12)
    builtin.module {
      func.func @main$async_dispatch_21_batch_matmul_1x16x50257x2_f32() {
        %cst = arith.constant 0.000000e+00 : f32 loc("/local/mnt/workspace/compilers/CompilerLens/examples/sshleifer_tiny-gpt2/_full/ir_00_torch_input.mlir":48:11)
        %c0 = arith.constant 0 : index loc(unknown)
        %c128 = arith.constant 128 : index loc("/local/mnt/workspace/compilers/CompilerLens/examples/sshleifer_tiny-gpt2/_full/ir_00_torch_input.mlir":362:12)
        %0 = hal.interface.binding.subspan layout(<bindings = [#hal.pipeline.binding<storage_buffer, "ReadOnly|Indirect">, #hal.pipeline.binding<storage_buffer, ReadOnly>, #hal.pipeline.binding<storage_buffer, Indirect>], flags = Indirect>) binding(0) alignment(64) offset(%c0) flags("ReadOnly|Indirect") : !iree_tensor_ext.dispatch.tensor<readonly:tensor<1x16x2xf32>> loc("/local/mnt/workspace/compilers/CompilerLens/examples/sshleifer_tiny-gpt2/_full/ir_00_torch_input.mlir":354:12)
        %1 = hal.interface.binding.subspan layout(<bindings = [#hal.pipeline.binding<storage_buffer, "ReadOnly|Indirect">, #hal.pipeline.binding<storage_buffer, ReadOnly>, #hal.pipeline.binding<storage_buffer, Indirect>], flags = Indirect>) binding(1) alignment(64) offset(%c128) flags(ReadOnly) : !iree_tensor_ext.dispatch.tensor<readonly:tensor<1x2x50257xf32>> loc("/local/mnt/workspace/compilers/CompilerLens/examples/sshleifer_tiny-gpt2/_full/ir_00_torch_input.mlir":362:12)
        %2 = hal.interface.binding.subspan layout(<bindings = [#hal.pipeline.binding<storage_buffer, "ReadOnly|Indirect">, #hal.pipeline.binding<storage_buffer, ReadOnly>, #hal.pipeline.binding<storage_buffer, Indirect>], flags = Indirect>) binding(2) alignment(64) offset(%c0) flags(Indirect) : !iree_tensor_ext.dispatch.tensor<writeonly:tensor<1x16x50257xf32>> loc("/local/mnt/workspace/compilers/CompilerLens/examples/sshleifer_tiny-gpt2/_full/ir_00_torch_input.mlir":362:12)
        %3 = iree_tensor_ext.dispatch.tensor.load %0, offsets = [0, 0, 0], sizes = [1, 16, 2], strides = [1, 1, 1] : !iree_tensor_ext.dispatch.tensor<readonly:tensor<1x16x2xf32>> -> tensor<1x16x2xf32> loc("/local/mnt/workspace/compilers/CompilerLens/examples/sshleifer_tiny-gpt2/_full/ir_00_torch_input.mlir":362:12)
        %4 = iree_tensor_ext.dispatch.tensor.load %1, offsets = [0, 0, 0], sizes = [1, 2, 50257], strides = [1, 1, 1] : !iree_tensor_ext.dispatch.tensor<readonly:tensor<1x2x50257xf32>> -> tensor<1x2x50257xf32> loc("/local/mnt/workspace/compilers/CompilerLens/examples/sshleifer_tiny-gpt2/_full/ir_00_torch_input.mlir":362:12)
        %5 = tensor.empty() : tensor<1x16x50257xf32> loc("/local/mnt/workspace/compilers/CompilerLens/examples/sshleifer_tiny-gpt2/_full/ir_00_torch_input.mlir":362:12)
        %6 = linalg.fill ins(%cst : f32) outs(%5 : tensor<1x16x50257xf32>) -> tensor<1x16x50257xf32> loc("/local/mnt/workspace/compilers/CompilerLens/examples/sshleifer_tiny-gpt2/_full/ir_00_torch_input.mlir":362:12)
        %7 = linalg.batch_matmul ins(%3, %4 : tensor<1x16x2xf32>, tensor<1x2x50257xf32>) outs(%6 : tensor<1x16x50257xf32>) -> tensor<1x16x50257xf32> loc("/local/mnt/workspace/compilers/CompilerLens/examples/sshleifer_tiny-gpt2/_full/ir_00_torch_input.mlir":362:12)
        iree_tensor_ext.dispatch.tensor.store %7, %2, offsets = [0, 0, 0], sizes = [1, 16, 50257], strides = [1, 1, 1] : tensor<1x16x50257xf32> -> !iree_tensor_ext.dispatch.tensor<writeonly:tensor<1x16x50257xf32>> loc("/local/mnt/workspace/compilers/CompilerLens/examples/sshleifer_tiny-gpt2/_full/ir_00_torch_input.mlir":362:12)
        return loc("/local/mnt/workspace/compilers/CompilerLens/examples/sshleifer_tiny-gpt2/_full/ir_00_torch_input.mlir":362:12)
      } loc("/local/mnt/workspace/compilers/CompilerLens/examples/sshleifer_tiny-gpt2/_full/ir_00_torch_input.mlir":362:12)
    } loc("/local/mnt/workspace/compilers/CompilerLens/examples/sshleifer_tiny-gpt2/_full/ir_00_torch_input.mlir":362:12)
  } loc("/local/mnt/workspace/compilers/CompilerLens/examples/sshleifer_tiny-gpt2/_full/ir_00_torch_input.mlir":362:12)
} loc("/local/mnt/workspace/compilers/CompilerLens/examples/sshleifer_tiny-gpt2/_full/ir_00_torch_input.mlir":362:12)
